const levelNames={1:'Básico',2:'Intermediário',3:'Avançado',4:'Especialista'};
let cases=[],i=0,hits=0,streak=0,locked=false,startX=0,dragX=0,reviewMode=false,currentLevel='progressive';
const $=id=>document.getElementById(id),card=$('card'),overlay=$('overlay');
const store=JSON.parse(localStorage.getItem('nuvemTraining')||'{"total":0,"correct":0,"bestStreak":0,"skills":{},"errors":[],"days":{}}');
const save=()=>localStorage.setItem('nuvemTraining',JSON.stringify(store));
function shuffle(a){a=[...a];for(let j=a.length-1;j>0;j--){const k=Math.floor(Math.random()*(j+1));[a[j],a[k]]=[a[k],a[j]]}return a}
function buildSession(level='progressive',count=12){if(level==='progressive'){const out=[];[1,2,3,4].forEach(d=>out.push(...shuffle(baseCases.filter(c=>c.difficulty===d)).slice(0,3)));return out}return shuffle(baseCases.filter(c=>c.difficulty===Number(level))).slice(0,Math.min(count,baseCases.filter(c=>c.difficulty===Number(level)).length))}
function chartSvg(c,feedback=false){const W=620,H=280,p={l:42,r:18,t:20,b:38};const max=Math.max(50,...c.h2,...c.ch4,c.marker?.value||0)+10,x=v=>p.l+(v/Math.max(...c.t))*(W-p.l-p.r),y=v=>H-p.b-(v/max)*(H-p.t-p.b);let grid='';for(let k=0;k<=5;k++){const val=Math.round(max*k/5),yy=y(val);grid+=`<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" stroke="#e5eaed"/><text x="${p.l-8}" y="${yy+4}" fill="#71808b" font-size="10" text-anchor="end">${val}</text>`}let xt='';c.t.forEach(v=>xt+=`<text x="${x(v)}" y="${H-14}" fill="#71808b" font-size="10" text-anchor="middle">${v}</text>`);const pts=a=>a.map((v,j)=>`${x(c.t[j])},${y(v)}`).join(' ');let ann='';if(feedback&&c.marker){const m=c.marker;if(m.kind==='threshold'||m.kind==='delta'){const val=m.value;ann+=`<line x1="${p.l}" y1="${y(val)}" x2="${W-p.r}" y2="${y(val)}" stroke="#b25b56" stroke-width="2" stroke-dasharray="6 5"/><text x="${W-p.r-4}" y="${y(val)-6}" text-anchor="end" fill="#b25b56" font-size="11">limiar ${val} ppm</text>`}if(m.kind==='time'){ann+=`<line x1="${x(m.time)}" y1="${p.t}" x2="${x(m.time)}" y2="${H-p.b}" stroke="#b25b56" stroke-width="2" stroke-dasharray="6 5"/><text x="${x(m.time)+5}" y="${p.t+12}" fill="#b25b56" font-size="11">${m.time} min</text>`}if(m.kind==='point'){const arr=m.gas==='ch4'?c.ch4:c.h2;const idx=c.t.indexOf(m.time);if(idx>=0)ann+=`<circle cx="${x(m.time)}" cy="${y(arr[idx])}" r="9" fill="none" stroke="#b25b56" stroke-width="3"/><text x="${x(m.time)+12}" y="${y(arr[idx])-10}" fill="#b25b56" font-size="11">ponto crítico</text>`}if(m.kind==='flat'){ann+=`<text x="${W/2}" y="${p.t+14}" text-anchor="middle" fill="#b25b56" font-size="11">curva persistentemente baixa/zerada: checar qualidade ou não respondedor</text>`}}return `<svg viewBox="0 0 ${W} ${H}" width="100%" role="img">${grid}<line x1="${p.l}" y1="${H-p.b}" x2="${W-p.r}" y2="${H-p.b}" stroke="#cbd4da"/>${xt}<polyline fill="none" stroke="#285f6f" stroke-width="4" points="${pts(c.h2)}"/><polyline fill="none" stroke="#6ca9a7" stroke-width="4" stroke-dasharray="8 7" points="${pts(c.ch4)}"/>${c.h2.map((v,j)=>`<circle cx="${x(c.t[j])}" cy="${y(v)}" r="4" fill="#285f6f"/>`).join('')}${c.ch4.map((v,j)=>`<circle cx="${x(c.t[j])}" cy="${y(v)}" r="4" fill="#6ca9a7"/>`).join('')}${ann}</svg>`}
function renderPreview(){const n=cases[i+1];const p=$('nextCardPreview');if(!n){p.style.display='none';return}p.style.display='block';$('nextCaseType').textContent=n.type;$('nextLevel').textContent=levelNames[n.difficulty];$('nextClaim').textContent=n.claim}
function render(){const c=cases[i];$('caseNum').textContent=`CASO ${i+1} DE ${cases.length}${reviewMode?' · REVISÃO':''}`;$('testType').textContent=c.type;$('levelChip').textContent=levelNames[c.difficulty];$('claim').textContent=c.claim;$('chart').innerHTML=chartSvg(c);$('meta').innerHTML=c.meta.map((m,j)=>`<div><b>${['Substrato/Exame','Referência','Contexto'][j]}</b><span>${m}</span></div>`).join('');$('progressBar').style.width=`${(i/cases.length)*100}%`;$('bankNote').textContent=`Banco: ${baseCases.length} casos · sessão atual: ${cases.length} · ${currentLevel==='progressive'?'progressão do básico ao especialista':levelNames[currentLevel]}`;renderPreview();resetCard()}
function resetCard(){card.style.transition='transform .18s ease,opacity .18s ease';card.style.transform='translateX(0) rotate(0)';card.style.opacity='1';$('stampYes').style.opacity=0;$('stampNo').style.opacity=0;locked=false}
function choose(val){if(locked)return;locked=true;const c=cases[i],ok=val===c.answer;if(ok){hits++;streak++}else streak=0;store.total++;if(ok)store.correct++;store.bestStreak=Math.max(store.bestStreak,streak);store.skills[c.category]??={n:0,ok:0};store.skills[c.category].n++;if(ok)store.skills[c.category].ok++;const errKey=c.id;if(!ok&&!store.errors.includes(errKey))store.errors.push(errKey);if(ok&&reviewMode)store.errors=store.errors.filter(x=>x!==errKey&&x!==c.claim);const day=new Date().toISOString().slice(0,10);store.days[day]=(store.days[day]||0)+1;save();$('hits').textContent=hits;$('streak').textContent=streak;$('scorePct').textContent=Math.round(hits/(i+1)*100);const exit=(window.innerWidth+card.getBoundingClientRect().width+160)*(val?1:-1);card.style.transition='transform .34s cubic-bezier(.22,.72,.2,1),opacity .3s ease';card.style.transform=`translateX(${exit}px) rotate(${val?22:-22}deg)`;card.style.opacity='0';setTimeout(()=>{$('resultIcon').className='result-icon '+(ok?'ok':'err');$('resultIcon').textContent=ok?'✓':'✕';$('resultTitle').textContent=ok?'Resposta correta':'Resposta incorreta';$('mistakeTitle').textContent=ok?'Ponto de confirmação':'Onde você errou';$('resultLead').textContent=ok?'A interpretação está de acordo com o critério treinado.':'Veja exatamente qual elemento mudou a classificação.';$('errorMap').innerHTML=`<div class="error-cell"><b>Sua resposta</b>${val?'Correta / positiva':'Incorreta / negativa'}</div><div class="error-cell"><b>Esperado</b>${c.answer?'Correta / positiva':'Incorreta / negativa'}</div><div class="error-cell"><b>Ponto decisivo</b>${c.short}</div><div class="error-cell"><b>Nível</b>${levelNames[c.difficulty]}</div>`;$('feedbackChart').innerHTML=chartSvg(c,true);$('resultWhy').textContent=c.why;$('detailsBox').textContent=c.detail;$('detailsBox').classList.remove('show');$('detailsToggle').textContent='Entender o raciocínio ↓';overlay.classList.add('show')},360)}
function next(){overlay.classList.remove('show');i++;if(i>=cases.length){card.style.display='none';$('nextCardPreview').style.display='none';$('done').classList.add('show');$('progressBar').style.width='100%';const pct=Math.round(hits/cases.length*100);$('finalScore').textContent=pct+'%';$('finalText').textContent=`${hits} de ${cases.length} casos corretos. Melhor sequência histórica: ${store.bestStreak}.`;return}render()}
function resetGame(arr=null,isReview=false){cases=arr?[...arr]:buildSession(currentLevel);i=0;hits=0;streak=0;reviewMode=isReview;$('hits').textContent=0;$('streak').textContent=0;$('scorePct').textContent=0;$('done').classList.remove('show');card.style.display='block';render()}
function renderPerformance(){const cats=['SIBO','IMO','Lactose','Frutose','Sacarose','Qualidade'];$('skills').innerHTML=cats.map(k=>{const x=store.skills[k]||{n:0,ok:0},pct=x.n?Math.round(x.ok/x.n*100):0;return `<div class="skillrow"><div class="skilltop"><span>${k}</span><b>${x.n?pct+'%':'—'}</b></div><div class="skillbar"><i style="width:${pct}%"></i></div></div>`}).join('');const achievements=[['Primeiros passos',store.total>=1,'Complete 1 caso'],['Em ritmo',store.bestStreak>=5,'5 acertos consecutivos'],['100 casos',store.total>=100,'Complete 100 interpretações'],['Precisão clínica',store.total>=20&&store.correct/store.total>=.9,'≥90% após 20 casos'],['Explorador',Object.keys(store.skills).length>=5,'Treine 5 competências'],['Revisor',store.errors.length===0&&store.total>=10,'Zere sua fila de erros']];$('badges').innerHTML=achievements.map(a=>`<div class="badge ${a[1]?'unlocked':''}"><b>${a[1]?'✓ ':''}${a[0]}</b><br>${a[2]}</div>`).join('');const pct=store.total?Math.round(store.correct/store.total*100):0;$('trainingSummary').innerHTML=`<div class="scorebig">${pct}%</div><div class="small">precisão histórica · ${store.total} casos realizados</div><p class="daily">Hoje: <b>${store.days[new Date().toISOString().slice(0,10)]||0}</b> casos. Desafio diário: 5 casos.</p>`;$('bestStreak').textContent=store.bestStreak;$('streakMessage').textContent=store.bestStreak>=5?'🔥 Sequência consistente. Continue tentando superar seu recorde.':'A sequência cresce a cada resposta correta consecutiva.'}
function renderReview(){const n=store.errors.length;$('reviewText').innerHTML=n?`Você tem <b>${n}</b> conceito${n>1?'s':''} na fila. A revisão reapresenta os casos errados e remove um item quando ele é respondido corretamente.`:'Sua fila está vazia. Novos erros aparecerão aqui automaticamente para revisão espaçada.';$('startReview').disabled=!n}
const library=[['SIBO','H₂','Elevação de H₂ >20 ppm acima do basal até 90 min. A elevação apenas aos 120 min pode refletir chegada do substrato ao cólon. Sintomas não são obrigatórios.'],['IMO','CH₄','CH₄ ≥10 ppm em qualquer momento da monitorização, inclusive basal, sustenta IMO. Sintomas não são necessários para o critério apresentado.'],['Lactose','H₂ / sintomas','H₂ ≥20 ppm acima do basal indica má absorção; com sintomas, o material classifica como intolerância. H₂ baixo com sintomas levanta não respondedor e repetição com CH₄.'],['Frutose','H₂ / sintomas','Dose descrita: 1 g/kg, máximo 25 g; leituras a cada 30 min até 180. Elevação de H₂ ≥20 ppm acima do basal sem sintomas = má absorção; com sintomas = intolerância.'],['Sacarose','H₂ / qualidade','Dose 0,5–1 g/kg, máximo 25 g; leituras até 180 min. O material destaca que erro no registro da primeira leitura basal desloca o limiar do gráfico.'],['Qualidade técnica','Antes do diagnóstico','Queda isolada em curva ascendente pode indicar sopro fraco: repetir leitura e checar qualidade. Leituras zeradas podem indicar calibração ou não respondedor ao H₂; considerar H₂–CH₄.']];
$('libraryGrid').innerHTML=library.map(x=>`<article class="topic"><div class="tag">${x[1]}</div><h3>${x[0]}</h3><p>${x[2]}</p></article>`).join('');
$('detailsToggle').onclick=()=>{const d=$('detailsBox');d.classList.toggle('show');$('detailsToggle').textContent=d.classList.contains('show')?'Ocultar raciocínio ↑':'Entender o raciocínio ↓'};
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.view;$('gameView').style.display=v==='game'?'block':'none';['performance','review','library'].forEach(x=>$(x+'View').classList.toggle('show',v===x));if(v==='performance')renderPerformance();if(v==='review')renderReview()});
$('startReview').onclick=()=>{const arr=baseCases.filter(c=>store.errors.includes(c.id)||store.errors.includes(c.claim));document.querySelector('[data-view="game"]').click();resetGame(arr,true)};
$('dailyBtn').onclick=()=>{document.querySelector('[data-view="game"]').click();const seed=Number(new Date().toISOString().slice(0,10).replaceAll('-',''));const arr=[...baseCases].sort((a,b)=>((a.id.length*97+seed)%101)-((b.id.length*97+seed)%101)).slice(0,5);resetGame(arr,false)};
document.querySelectorAll('.levelbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.levelbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentLevel=b.dataset.level;reviewMode=false;resetGame()});
$('yesBtn').onclick=()=>choose(true);$('noBtn').onclick=()=>choose(false);$('continueBtn').onclick=next;$('restart').onclick=()=>resetGame();
card.addEventListener('pointerdown',e=>{if(locked||e.target.closest('.actions'))return;startX=e.clientX;dragX=0;card.setPointerCapture(e.pointerId);card.classList.add('dragging')});card.addEventListener('pointermove',e=>{if(!startX||locked)return;dragX=e.clientX-startX;card.style.transform=`translateX(${dragX}px) rotate(${dragX/25}deg)`;$('stampYes').style.opacity=Math.max(0,Math.min(1,dragX/120));$('stampNo').style.opacity=Math.max(0,Math.min(1,-dragX/120))});card.addEventListener('pointerup',()=>{card.classList.remove('dragging');startX=0;if(Math.abs(dragX)>110)choose(dragX>0);else resetCard();dragX=0});card.addEventListener('pointercancel',()=>{startX=0;dragX=0;card.classList.remove('dragging');if(!locked)resetCard()});
document.addEventListener('keydown',e=>{if(overlay.classList.contains('show')){if(e.key==='Enter')next();return}if(e.key==='ArrowRight')choose(true);if(e.key==='ArrowLeft')choose(false)});resetGame();